; PlatformIO Project Configuration File
;
;   Build options: build flags, build filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO

board_build.cpp_std = gnu++17
; Дополнительно к cpp_std (на некоторых ядрах avr)
build_flags = -std=gnu++17

upload_port = /dev/ttyUSB0
upload_speed = 57600
